# Generated by Django 5.1.4 on 2024-12-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("comment", models.TextField(max_length=2047)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=2047)),
                ("preview", models.ImageField(upload_to="preview/%y/%m/%d")),
                ("year_of_release", models.IntegerField()),
                ("premiere", models.DateField()),
                ("country", models.CharField(max_length=63)),
                ("movie", models.FileField(upload_to="music/%Y/%m/%d/")),
                ("mark", models.FloatField()),
                ("is_eighteen", models.BooleanField()),
                ("director", models.CharField(verbose_name=127)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.comment",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.genre"
                    ),
                ),
            ],
        ),
    ]
