# Generated by Django 5.1.4 on 2024-12-22 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="film",
            old_name="preview",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="film",
            name="comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="film",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.film",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="film",
            name="director",
            field=models.CharField(),
        ),
        migrations.RemoveField(
            model_name="film",
            name="genre",
        ),
        migrations.AlterField(
            model_name="film",
            name="movie",
            field=models.FileField(upload_to="film/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="film",
            name="genre",
            field=models.ManyToManyField(to="catalog.genre"),
        ),
    ]
